<a href="https://colab.research.google.com/github/devincriniti/DSC_110/blob/main/IN%20CLASS/dsc_110_prediction_week_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA PREP FOR MACHINE LEARNING/PREDICTION

In [192]:
##here we are importing pandas and the scikit-learn library's train_test_split function
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [193]:
## here we are reading the csv file/the dataset
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [194]:
## here we are making sure the data is there, by looking at the first 5 rows.
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

1- filtering

In [195]:
# here we are filtering out the data to included only records that have a specific age range- we use copy to prevent from overriding the date
df = df[df['age'] >= 18].copy()

In [196]:
## here we are varifying that our last line of code worked, we are doing this by looking at the minimum age in the data
df['age'].min()

18.0

In [197]:
## here we are looking at how many rows and collumns are in the data frame after filtering
df.shape

(8153, 11)

2- dropping columns

In [198]:
## here we are getting rid of fields that are irrelevant to what we are trying to predict
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'])

In [199]:
## here we are varifying that the columns were actually dropped
df.shape

(8153, 8)

3- mapping labels

In [200]:
## here we are "mapping labels" which basically means we are making the data more meaningful by putting words in place of the numbers (which are used to save space in the dataset)

In [201]:
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

In [202]:
##here we are changing the numbers to the labels (male and female) within the data, we are linking the map to the data
df['gender'] = df['gender'].map(gender_map)

In [203]:
##here we are varifying the labels were changed

df['gender'].head()

0      Male
1      Male
2    Female
6      Male
7    Female
Name: gender, dtype: object

In [204]:
##here we are changing the numbers to the labels (different races) within the data, we are linking the map to the data

df['race_ethnicity'] = df['race_ethnicity'].map(race_map)

In [205]:
##here we are varifying the labels were changed

df['race_ethnicity'].head()

0               Asian
1               White
2      Other Hispanic
6    Mexican American
7               White
Name: race_ethnicity, dtype: object

In [206]:
##here we are changing the numbers to the labels (different education) within the data, we are linking the map to the data

df['education'] = df['education'].map(education_map)

In [207]:
##here we are varifying the labels were changed
df['education'].head()

0    College grad
1    College grad
2     High school
6    9-11th grade
7     High school
Name: education, dtype: object

4-missing values

In [208]:
##checking for missing values - tells us how many values are missing in each field
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education          359
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [209]:
#here we are filling the missing bmi data with the mean of the data
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [210]:
#checking
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education          359
bmi                  0
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [211]:
#here we are filling the missing height data with the mean of the data
df['height_cm'] = df['height_cm'].fillna(df['height_cm'].mean())

In [212]:
#checking
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education          359
bmi                  0
height_cm            0
systolic_bp       2030
has_diabetes         3
dtype: int64

In [213]:
#here we are filling the missing systolic bp data with the mean of the data
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

In [214]:
#checking
df.isna().sum()

gender              0
age                 0
race_ethnicity      0
education         359
bmi                 0
height_cm           0
systolic_bp         0
has_diabetes        3
dtype: int64

In [215]:
## here we are removing the data within the education variable
df = df.dropna(subset=['education']).copy()

In [216]:
#checking to make sure the missing education data is no longer there
df.isna().sum()

gender            0
age               0
race_ethnicity    0
education         0
bmi               0
height_cm         0
systolic_bp       0
has_diabetes      0
dtype: int64

5- defining the target variable

In [217]:
#here we are defining the target variable & changing the has diabetes and no diabetes from 1.0 and 2.0 to 0 and 1

In [218]:
# here we are filtering out the rows that arent "has diabetes" and "no diabetes"
df = df[df['has_diabetes'].isin([1.0, 2.0])].copy()

In [219]:
# here we are changing the numerical represantion of has diabetes and no diabetes from 1 & 2 to 0 and 1
df['has_diabetes'] = df['has_diabetes'].map({1.0: 1, 2.0: 0})

In [220]:
# here we are checking the shape of the data
df.shape

(7523, 8)

6 - One hot encoding

In [221]:
## here we are converting the categorical variable into two numerical columns -> gender (male or female) to gender_female (0/1) to gender_male (0/1)
df = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'education'],
                    drop_first=True)

In [222]:
##checking
df.head()

,age,bmi,height_cm,systolic_bp,has_diabetes,gender_Male,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
0,43.0,27.000000,179.500000,135.000000,0,True,False,False,False,False,False,True,False,False,False,False
1,66.0,33.500000,174.200000,121.000000,0,True,False,False,False,False,True,True,False,False,False,False
2,44.0,29.700000,152.900000,111.000000,1,False,False,False,False,True,False,False,False,True,False,False
6,43.0,29.659326,166.954982,122.561653,0,True,False,True,False,False,False,False,False,False,False,False
7,65.0,29.659326,166.954982,122.561653,0,False,False,False,False,False,True,False,False,True,False,False

7 - scaling numeric values

In [223]:
## here we are changing the data to be based around the mean, instead of actual values the value will be represented based on distance from mean

In [224]:
## here we are defining which fields are numeric
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']

In [225]:
## here we are defining the standar scaler function as scaler
scaler = StandardScaler()

In [226]:
## here we are applying the scaler function to all the numeric data/columns
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [227]:
##checking to make sure its scaled values instead of the actual values
df[numeric_cols].head()

        age       bmi  height_cm  systolic_bp
0 -0.589355 -0.425106   1.424574     0.758296
1  0.719517  0.589889   0.823127    -0.115670
2 -0.532448 -0.003493  -1.594009    -0.739931
6 -0.589355 -0.009844   0.000959    -0.018182
7  0.662610 -0.009844   0.000959    -0.018182

In [228]:
##making sure the mean is 0
print(round(df['age'].mean(),2))

0.0

In [229]:
#making sure SD is 1
df['age'].std()

1.0000664694739656

8 - Train/Test Split

In [230]:
## here we are testing how well our model performs with new data  and are splitting our data in y and x , y= outcome/ target,  x = variables
X = df.drop(columns=['has_diabetes'])
y = df['has_diabetes']

In [231]:
## here we are splitting the data into 4 data frames - the x/y train and test subset, we are also making sure that 20% of the data is used for the testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [234]:
##checking
X_train.head()

,age,bmi,height_cm,systolic_bp,gender_Male,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
6225,0.321165,0.183891,-1.310308,0.446166,False,False,False,False,False,True,False,False,True,False,False
8518,0.776425,-1.080948,-0.062021,-0.739931,False,False,False,False,False,True,False,False,True,False,False
5532,0.548795,1.885958,1.061437,0.633444,False,True,False,False,False,False,True,False,False,False,False
7314,1.459315,-0.009844,0.000959,-0.018182,False,False,False,False,False,True,False,False,False,True,False
9913,-0.987708,-0.987256,0.494034,-0.178096,True,False,False,False,True,False,False,False,False,True,False